/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import javax.swing.ImageIcon;

/**
 *
 * @author Administrator
 */
public class LevelPage extends javax.swing.JFrame {

    /**
     * Creates new form LevelPage
     */
    public LevelPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backLevelPageButton = new javax.swing.JLabel();
        easyButton = new javax.swing.JLabel();
        normalButton = new javax.swing.JLabel();
        hardButton = new javax.swing.JLabel();
        pageBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        backLevelPageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/backButton.png"))); // NOI18N
        backLevelPageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLevelPageButtonMouseClicked(evt);
            }
        });
        getContentPane().add(backLevelPageButton);
        backLevelPageButton.setBounds(140, 210, 130, 50);

        easyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/easyButton.png"))); // NOI18N
        easyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                easyButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                easyButtonMouseExited(evt);
            }
        });
        getContentPane().add(easyButton);
        easyButton.setBounds(140, 30, 130, 50);

        normalButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/normalButton.png"))); // NOI18N
        normalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                normalButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                normalButtonMouseExited(evt);
            }
        });
        getContentPane().add(normalButton);
        normalButton.setBounds(140, 90, 130, 50);

        hardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/hardButton.png"))); // NOI18N
        hardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hardButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hardButtonMouseExited(evt);
            }
        });
        getContentPane().add(hardButton);
        hardButton.setBounds(140, 150, 130, 50);

        pageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/windowBackground3.png"))); // NOI18N
        pageBackground.setText("jLabel4");
        getContentPane().add(pageBackground);
        pageBackground.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void easyButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyButtonMouseEntered
        ImageIcon easyIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/easyButtonHover.png"));
        easyButton.setIcon(easyIcon);
    }//GEN-LAST:event_easyButtonMouseEntered

    private void easyButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easyButtonMouseExited
         ImageIcon easyIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/easyButton.png"));
        easyButton.setIcon(easyIcon);
    }//GEN-LAST:event_easyButtonMouseExited

    private void normalButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_normalButtonMouseEntered
        ImageIcon normalIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/normalButtonHover.png"));
        normalButton.setIcon(normalIcon);
    }//GEN-LAST:event_normalButtonMouseEntered

    private void normalButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_normalButtonMouseExited
        ImageIcon normalIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/normalButton.png"));
        normalButton.setIcon(normalIcon);
    }//GEN-LAST:event_normalButtonMouseExited

    private void hardButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardButtonMouseEntered
        ImageIcon hardIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/hardButtonHover.png"));
        hardButton.setIcon(hardIcon);
    }//GEN-LAST:event_hardButtonMouseEntered

    private void hardButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardButtonMouseExited
        ImageIcon hardIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/hardButton.png"));
        hardButton.setIcon(hardIcon);
    }//GEN-LAST:event_hardButtonMouseExited

    private void backLevelPageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLevelPageButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_backLevelPageButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LevelPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LevelPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LevelPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LevelPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LevelPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backLevelPageButton;
    private javax.swing.JLabel easyButton;
    private javax.swing.JLabel hardButton;
    private javax.swing.JLabel normalButton;
    private javax.swing.JLabel pageBackground;
    // End of variables declaration//GEN-END:variables
}
