/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import java.awt.Frame;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import nz.ac.aut.ense701.gameModel.Game;

/**
 *
 * @author Administrator
 */
public class TitlePage extends javax.swing.JFrame {

    /**
     * Creates new form titlePage
     */
    public TitlePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        exitButton = new javax.swing.JLabel();
        playAsVisitorTitlePageButton = new javax.swing.JLabel();
        loginTitlePageButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 502));
        setResizable(false);
        getContentPane().setLayout(null);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/exitButton.png"))); // NOI18N
        exitButton.setText("jLabel4");
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(130, 440, 150, 30);

        playAsVisitorTitlePageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/playAsVisitorTitlePageButton.png"))); // NOI18N
        playAsVisitorTitlePageButton.setText("jLabel3");
        playAsVisitorTitlePageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playAsVisitorTitlePageButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playAsVisitorTitlePageButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playAsVisitorTitlePageButtonMouseExited(evt);
            }
        });
        getContentPane().add(playAsVisitorTitlePageButton);
        playAsVisitorTitlePageButton.setBounds(130, 390, 150, 30);

        loginTitlePageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/loginTitlePageButton.png"))); // NOI18N
        loginTitlePageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginTitlePageButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginTitlePageButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginTitlePageButtonMouseExited(evt);
            }
        });
        getContentPane().add(loginTitlePageButton);
        loginTitlePageButton.setBounds(130, 340, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/titlePageBackground.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 500);

        pack();
    }// </editor-fold>                        

    private void loginTitlePageButtonMouseEntered(java.awt.event.MouseEvent evt) {                                                  
        ImageIcon loginTitlePageIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/loginTitlePageButtonHover.png"));
        loginTitlePageButton.setIcon(loginTitlePageIcon);
    }                                                 

    private void loginTitlePageButtonMouseExited(java.awt.event.MouseEvent evt) {                                                 
        ImageIcon loginTitlePageIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/loginTitlePageButton.png"));
        loginTitlePageButton.setIcon(loginTitlePageIcon);
    }                                                

    private void playAsVisitorTitlePageButtonMouseEntered(java.awt.event.MouseEvent evt) {                                                          
       ImageIcon playAsVisitorTitlePageIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/playAsVisitorTitlePageButtonHover.png"));
        playAsVisitorTitlePageButton.setIcon(playAsVisitorTitlePageIcon);
    }                                                         

    private void playAsVisitorTitlePageButtonMouseExited(java.awt.event.MouseEvent evt) {                                                         
        ImageIcon playAsVisitorTitlePageIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/playAsVisitorTitlePageButton.png"));
        playAsVisitorTitlePageButton.setIcon(playAsVisitorTitlePageIcon);
    }                                                        

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {                                        
        ImageIcon exitIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/exitButtonHover.png"));
        exitButton.setIcon(exitIcon);
    }                                       

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {                                       
        ImageIcon exitIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/exitButton.png"));
        exitButton.setIcon(exitIcon);
    }                                      

    private void loginTitlePageButtonMouseClicked(java.awt.event.MouseEvent evt) {                                                  
        LoginPage lg = new LoginPage();
                lg.setVisible(true);
                lg.setSize(400,326);
                lg.setLocationRelativeTo(null);
                lg.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(false);
    }                                                 

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {                                        
         ExitComfirmPage ecp = new ExitComfirmPage();
                ecp.setVisible(true);
                ecp.setSize(400,300);
                ecp.setLocationRelativeTo(null);
                ecp.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }                                       

    private void playAsVisitorTitlePageButtonMouseClicked(java.awt.event.MouseEvent evt) {                                                          
        String difficulty = "";
        final Game game = new Game(difficulty);
        final KiwiCountUI  gui  = new KiwiCountUI(game);
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            @Override
            public void run() 
            {
                gui.setVisible(true);
            }
        });
        this.setVisible(false);        
    }                                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TitlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TitlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TitlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TitlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TitlePage tp = new TitlePage(); 
                tp.setLocationRelativeTo(null);
                tp.setSize(400,510);
                tp.setVisible(true);
                 
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel loginTitlePageButton;
    private javax.swing.JLabel playAsVisitorTitlePageButton;
    // End of variables declaration                   
}
