package nz.ac.aut.ense701.gui;

import javax.swing.ImageIcon;
import nz.ac.aut.ense701.gameModel.*;

/**
 *
 * @author Administrator
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        userLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JFormattedTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JLabel();
        registerButton = new javax.swing.JLabel();
        playAsVisitorButton = new javax.swing.JLabel();
        loginPageBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        userLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userLabel.setForeground(new java.awt.Color(153, 74, 2));
        userLabel.setText("User Name: ");
        userLabel.setToolTipText("");
        getContentPane().add(userLabel);
        userLabel.setBounds(50, 50, 90, 20);
        getContentPane().add(userNameTextField);
        userNameTextField.setBounds(150, 50, 160, 21);

        passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(153, 74, 2));
        passwordLabel.setText("Password:");
        getContentPane().add(passwordLabel);
        passwordLabel.setBounds(50, 90, 80, 17);
        getContentPane().add(passwordField);
        passwordField.setBounds(150, 90, 160, 21);

        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/loginButton.png"))); // NOI18N
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginButtonMouseExited(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(50, 160, 125, 48);

        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/registerButton.png"))); // NOI18N
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerButtonMouseExited(evt);
            }
        });
        getContentPane().add(registerButton);
        registerButton.setBounds(230, 160, 125, 48);

        playAsVisitorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/playAsVisitorButton.png"))); // NOI18N
        playAsVisitorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playAsVisitorButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playAsVisitorButtonMouseEntered(evt);
            }
        });
        getContentPane().add(playAsVisitorButton);
        playAsVisitorButton.setBounds(140, 230, 125, 48);

        loginPageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/windowBackground3.png"))); // NOI18N
        getContentPane().add(loginPageBackground);
        loginPageBackground.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>                        

    private void loginButtonMouseEntered(java.awt.event.MouseEvent evt) {                                         
        ImageIcon loginIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/loginButtonHover.png"));
        loginButton.setIcon(loginIcon);
    }                                        

    private void loginButtonMouseExited(java.awt.event.MouseEvent evt) {                                        
        ImageIcon loginIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/loginButton.png"));
        loginButton.setIcon(loginIcon);
    }                                       

    private void registerButtonMouseEntered(java.awt.event.MouseEvent evt) {                                            
       ImageIcon registerIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/registerButtonHover.png"));
        registerButton.setIcon(registerIcon);
    }                                           

    private void registerButtonMouseExited(java.awt.event.MouseEvent evt) {                                           
       ImageIcon registerIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/registerButton.png"));
        registerButton.setIcon(registerIcon);
    }                                          

    private void playAsVisitorButtonMouseEntered(java.awt.event.MouseEvent evt) {                                                 
        ImageIcon playAsVisitorIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/playAsVisitorButton.png"));
        playAsVisitorButton.setIcon(playAsVisitorIcon);
    }                                                

    private void playAsVisitorButtonMouseClicked(java.awt.event.MouseEvent evt) {                                                 
        final Game game = new Game();
        final KiwiCountUI  gui  = new KiwiCountUI(game);
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            @Override
            public void run() 
            {
                gui.setVisible(true);
            }
        });
    }                                                

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {                                            

        registerButton.setEnabled(false);
        if (userNameTextField.getText().isEmpty())
                {
                    userNameTextField.setText("Empty username!");
                }
                else if (!User.checkUsername(userNameTextField.getText()))
                {
                    userNameTextField.setText("Characters and numbers only!");
                }
                else if (User.hasUser(userNameTextField.getText()))
                {
                    userNameTextField.setText("User already exists!");
                }
                else
                {
                    if (User.addUser(userNameTextField.getText(),passwordField.getSelectedText()))
                    {
                        final Game game = new Game();
                        final KiwiCountUI  gui  = new KiwiCountUI(game);
                        java.awt.EventQueue.invokeLater(new Runnable() 
                        {
                            @Override
                            public void run() 
                            {
                                gui.setVisible(true);
                            }
                        });
                    }
                    else
                    {
                        userNameTextField.setText("Failed creating User!");
                    }
                }
        
    }                                           

      
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify                     
    private javax.swing.JLabel loginButton;
    private javax.swing.JLabel loginPageBackground;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel playAsVisitorButton;
    private javax.swing.JLabel registerButton;
    private javax.swing.JLabel userLabel;
    private javax.swing.JFormattedTextField userNameTextField;
    // End of variables declaration                   
}
