/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import javax.swing.ImageIcon;
import nz.ac.aut.ense701.gameModel.Game;

/**
 *
 * @author Administrator
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JFormattedTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JLabel();
        registerButton = new javax.swing.JLabel();
        playAsVisitorButton = new javax.swing.JLabel();
        loginPageBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        userLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userLabel.setForeground(new java.awt.Color(153, 74, 2));
        userLabel.setText("User Name: ");
        userLabel.setToolTipText("");
        getContentPane().add(userLabel);
        userLabel.setBounds(50, 50, 90, 20);
        getContentPane().add(userNameTextField);
        userNameTextField.setBounds(150, 50, 160, 20);

        passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(153, 74, 2));
        passwordLabel.setText("Password:");
        getContentPane().add(passwordLabel);
        passwordLabel.setBounds(50, 90, 80, 17);
        getContentPane().add(passwordField);
        passwordField.setBounds(150, 90, 160, 20);

        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/loginButton.png"))); // NOI18N
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginButtonMouseExited(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(50, 160, 125, 48);

        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/registerButton.png"))); // NOI18N
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerButtonMouseExited(evt);
            }
        });
        getContentPane().add(registerButton);
        registerButton.setBounds(230, 160, 125, 48);

        playAsVisitorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/playAsVisitorButton.png"))); // NOI18N
        playAsVisitorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playAsVisitorButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playAsVisitorButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playAsVisitorButtonMouseExited(evt);
            }
        });
        getContentPane().add(playAsVisitorButton);
        playAsVisitorButton.setBounds(140, 230, 125, 48);

        loginPageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/windowBackground3.png"))); // NOI18N
        getContentPane().add(loginPageBackground);
        loginPageBackground.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseEntered
        ImageIcon loginIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/loginButtonHover.png"));
        loginButton.setIcon(loginIcon);
    }//GEN-LAST:event_loginButtonMouseEntered

    private void loginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseExited
        ImageIcon loginIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/loginButton.png"));
        loginButton.setIcon(loginIcon);
    }//GEN-LAST:event_loginButtonMouseExited

    private void registerButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseEntered
       ImageIcon registerIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/registerButtonHover.png"));
        registerButton.setIcon(registerIcon);
    }//GEN-LAST:event_registerButtonMouseEntered

    private void registerButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseExited
       ImageIcon registerIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/registerButton.png"));
        registerButton.setIcon(registerIcon);
    }//GEN-LAST:event_registerButtonMouseExited

    private void playAsVisitorButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playAsVisitorButtonMouseEntered
        ImageIcon playAsVisitorIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/playAsVisitorButtonHover.png"));
        playAsVisitorButton.setIcon(playAsVisitorIcon);
    }//GEN-LAST:event_playAsVisitorButtonMouseEntered

    private void playAsVisitorButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playAsVisitorButtonMouseExited
        ImageIcon playAsVisitorIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/playAsVisitorButton.png"));
        playAsVisitorButton.setIcon(playAsVisitorIcon);
    }//GEN-LAST:event_playAsVisitorButtonMouseExited

    private void playAsVisitorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playAsVisitorButtonMouseClicked
        
    }//GEN-LAST:event_playAsVisitorButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel loginButton;
    private javax.swing.JLabel loginPageBackground;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel playAsVisitorButton;
    private javax.swing.JLabel registerButton;
    private javax.swing.JLabel userLabel;
    private javax.swing.JFormattedTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
