/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import nz.ac.aut.ense701.gameModel.*;

/**
 *
 * @author Administrator
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        userLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JFormattedTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JLabel();
        registerButton = new javax.swing.JLabel();
        backLoginPageButton = new javax.swing.JLabel();
        loginPageBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        userLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userLabel.setForeground(new java.awt.Color(153, 74, 2));
        userLabel.setText("User Name: ");
        userLabel.setToolTipText("");
        getContentPane().add(userLabel);
        userLabel.setBounds(50, 50, 90, 20);
        getContentPane().add(userNameTextField);
        userNameTextField.setBounds(150, 50, 160, 20);

        passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(153, 74, 2));
        passwordLabel.setText("Password:");
        getContentPane().add(passwordLabel);
        passwordLabel.setBounds(50, 90, 80, 17);
        getContentPane().add(passwordField);
        passwordField.setBounds(150, 90, 160, 20);

        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/loginButton.png"))); // NOI18N
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginButtonMouseExited(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(50, 160, 125, 48);

        registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/registerButton.png"))); // NOI18N
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registerButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registerButtonMouseExited(evt);
            }
        });
        getContentPane().add(registerButton);
        registerButton.setBounds(230, 160, 125, 48);

        backLoginPageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/backButton.png"))); // NOI18N
        backLoginPageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLoginPageButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backLoginPageButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backLoginPageButtonMouseExited(evt);
            }
        });
        getContentPane().add(backLoginPageButton);
        backLoginPageButton.setBounds(140, 230, 120, 46);

        loginPageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/windowBackground3.png"))); // NOI18N
        getContentPane().add(loginPageBackground);
        loginPageBackground.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>                        

    private void loginButtonMouseEntered(java.awt.event.MouseEvent evt) {                                         
        ImageIcon loginIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/loginButtonHover.png"));
        loginButton.setIcon(loginIcon);
    }                                        

    private void loginButtonMouseExited(java.awt.event.MouseEvent evt) {                                        
        ImageIcon loginIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/loginButton.png"));
        loginButton.setIcon(loginIcon);
    }                                       

    private void registerButtonMouseEntered(java.awt.event.MouseEvent evt) {                                            
       ImageIcon registerIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/registerButtonHover.png"));
        registerButton.setIcon(registerIcon);
    }                                           

    private void registerButtonMouseExited(java.awt.event.MouseEvent evt) {                                           
       ImageIcon registerIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/registerButton.png"));
        registerButton.setIcon(registerIcon);
    }                                          

    private void backLoginPageButtonMouseEntered(java.awt.event.MouseEvent evt) {                                                 
        ImageIcon backLoginPageIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/backButtonHover.png"));
        backLoginPageButton.setIcon(backLoginPageIcon);
    }                                                

    private void backLoginPageButtonMouseClicked(java.awt.event.MouseEvent evt) {                                                 
        this.dispose();
        TitlePage tp = new TitlePage();
            tp.setVisible(true);
            tp.setLocationRelativeTo(null);
    }                                                

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {                                            
        this.dispose();
        RegisterPage rp = new RegisterPage();
            rp.setVisible(true);
            rp.setSize(400,326);
            rp.setLocationRelativeTo(null);
            rp.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }                                           

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {                                         
        if(this.userNameTextField.getText().equals("") && this.passwordField.getPassword().length == 0){
            JOptionPane.showMessageDialog(
                this, 
                "Username and Password can not be empty!", "Empty username or password!",
                JOptionPane.INFORMATION_MESSAGE);
        }else{
            if(User.getUserByName(this.userNameTextField.getText()).getUsername().equals("")){
                JOptionPane.showMessageDialog(
                    this, 
                    "Username has not been registered!", "Wrong Username",
                    JOptionPane.INFORMATION_MESSAGE);
            }else if(!User.getUserByName(this.userNameTextField.getText()).getPassword().equals(String.valueOf(this.passwordField.getPassword()))){
                JOptionPane.showMessageDialog(
                    this, 
                    "Password is incorrect!", "Wrong Password!",
                    JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(
                        this, 
                        "Login successfully!", "Success!",
                        JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                LevelPage Lvp = new LevelPage();
                Lvp.setVisible(true);
                Lvp.setSize(400,326);
                Lvp.setLocationRelativeTo(null);
                Lvp.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            }
        }
    }                                        

    private void backLoginPageButtonMouseExited(java.awt.event.MouseEvent evt) {                                                
        ImageIcon backLoginPageIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/backButton.png"));
        backLoginPageButton.setIcon(backLoginPageIcon);
    }                                               

      
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify                     
    private javax.swing.JLabel backLoginPageButton;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel loginButton;
    private javax.swing.JLabel loginPageBackground;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel registerButton;
    private javax.swing.JLabel userLabel;
    private javax.swing.JFormattedTextField userNameTextField;
    // End of variables declaration                   
}
