/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import javax.swing.ImageIcon;

/**
 *
 * @author Administrator
 */
public class RegisterPage extends javax.swing.JFrame {

    /**
     * Creates new form registerPage
     */
    public RegisterPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JFormattedTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        confirmPasswordLabel = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        playButton = new javax.swing.JLabel();
        backReigisterPageButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        userLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userLabel.setForeground(new java.awt.Color(153, 74, 2));
        userLabel.setText("User Name: ");
        userLabel.setToolTipText("");
        getContentPane().add(userLabel);
        userLabel.setBounds(50, 50, 90, 30);
        getContentPane().add(userNameTextField);
        userNameTextField.setBounds(180, 50, 160, 30);

        passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(153, 74, 2));
        passwordLabel.setText("Password:");
        getContentPane().add(passwordLabel);
        passwordLabel.setBounds(60, 100, 80, 20);

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordField);
        passwordField.setBounds(180, 150, 160, 30);

        confirmPasswordLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        confirmPasswordLabel.setForeground(new java.awt.Color(153, 74, 2));
        confirmPasswordLabel.setText("Confirm Password:");
        getContentPane().add(confirmPasswordLabel);
        confirmPasswordLabel.setBounds(30, 150, 140, 20);

        confirmPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(confirmPasswordField);
        confirmPasswordField.setBounds(180, 100, 160, 30);

        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/playButton.png"))); // NOI18N
        playButton.setToolTipText("");
        playButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playButtonMouseExited(evt);
            }
        });
        getContentPane().add(playButton);
        playButton.setBounds(50, 220, 130, 50);

        backReigisterPageButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/backButton.png"))); // NOI18N
        backReigisterPageButton.setText("jLabel2");
        backReigisterPageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backReigisterPageButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backReigisterPageButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backReigisterPageButtonMouseExited(evt);
            }
        });
        getContentPane().add(backReigisterPageButton);
        backReigisterPageButton.setBounds(220, 220, 120, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/windowBackground3.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void playButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseEntered
        ImageIcon playIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/playButtonHover.png"));
        playButton.setIcon(playIcon);
    }//GEN-LAST:event_playButtonMouseEntered

    private void playButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseExited
        ImageIcon playIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/playButton.png"));
        playButton.setIcon(playIcon);
    }//GEN-LAST:event_playButtonMouseExited

    private void backReigisterPageButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backReigisterPageButtonMouseEntered
        ImageIcon backReigisterPageIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/backButtonHover.png"));
        backReigisterPageButton.setIcon(backReigisterPageIcon);
    }//GEN-LAST:event_backReigisterPageButtonMouseEntered

    private void backReigisterPageButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backReigisterPageButtonMouseExited
        ImageIcon backReigisterPageIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/backButton.png"));
        backReigisterPageButton.setIcon(backReigisterPageIcon);
    }//GEN-LAST:event_backReigisterPageButtonMouseExited

    private void backReigisterPageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backReigisterPageButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_backReigisterPageButtonMouseClicked

    private void playButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseClicked
        LevelPage lvp = new LevelPage();
            lvp.setVisible(true);
            lvp.setSize(400,326);
            lvp.setLocationRelativeTo(null);
            lvp.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_playButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backReigisterPageButton;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JLabel confirmPasswordLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel playButton;
    private javax.swing.JLabel userLabel;
    private javax.swing.JFormattedTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
