/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import java.awt.Frame;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Administrator
 */
public class TitlePage extends javax.swing.JFrame {

    /**
     * Creates new form titlePage
     */
    public TitlePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JLabel();
        tutorialButton = new javax.swing.JLabel();
        playButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 502));
        setResizable(false);
        getContentPane().setLayout(null);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/exitButton.png"))); // NOI18N
        exitButton.setText("jLabel4");
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(130, 440, 150, 30);

        tutorialButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/tutorialButton.png"))); // NOI18N
        tutorialButton.setText("jLabel3");
        tutorialButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tutorialButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tutorialButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tutorialButtonMouseExited(evt);
            }
        });
        getContentPane().add(tutorialButton);
        tutorialButton.setBounds(130, 390, 150, 30);

        playButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/playButton.png"))); // NOI18N
        playButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                playButtonMouseExited(evt);
            }
        });
        getContentPane().add(playButton);
        playButton.setBounds(130, 340, 150, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/titlePageBackground.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseEntered
        ImageIcon playIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/playButtonHover.png"));
        playButton.setIcon(playIcon);
    }//GEN-LAST:event_playButtonMouseEntered

    private void playButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseExited
        ImageIcon playIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/playButton.png"));
        playButton.setIcon(playIcon);
    }//GEN-LAST:event_playButtonMouseExited

    private void tutorialButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorialButtonMouseEntered
       ImageIcon tutorialIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/tutorialButtonHover.png"));
        tutorialButton.setIcon(tutorialIcon);
    }//GEN-LAST:event_tutorialButtonMouseEntered

    private void tutorialButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorialButtonMouseExited
        ImageIcon tutorialIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/tutorialButton.png"));
        tutorialButton.setIcon(tutorialIcon);
    }//GEN-LAST:event_tutorialButtonMouseExited

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        ImageIcon exitIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/exitButtonHover.png"));
        exitButton.setIcon(exitIcon);
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        ImageIcon exitIcon = new ImageIcon(getClass().getResource("/nz/ac/aut/ense701/gui/image/exitButton.png"));
        exitButton.setIcon(exitIcon);
    }//GEN-LAST:event_exitButtonMouseExited

    private void playButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButtonMouseClicked
        LoginPage lg = new LoginPage();
                lg.setVisible(true);
                lg.setSize(400,326);
                lg.setLocationRelativeTo(null);
                lg.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_playButtonMouseClicked

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
         ExitComfirmPage ecp = new ExitComfirmPage();
                ecp.setVisible(true);
                ecp.setSize(400,300);
                ecp.setLocationRelativeTo(null);
                ecp.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void tutorialButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorialButtonMouseClicked
         TutorialPage tp = new TutorialPage();
                tp.setVisible(true);
                tp.setSize(400,520);
                tp.setLocationRelativeTo(null);
                tp.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_tutorialButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TitlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TitlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TitlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TitlePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TitlePage tp = new TitlePage(); 
                tp.setLocationRelativeTo(null);
                tp.setSize(400,510);
                tp.setVisible(true);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel playButton;
    private javax.swing.JLabel tutorialButton;
    // End of variables declaration//GEN-END:variables
}
